# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Blog"
  url = "/post"
  weight = 20

[[main]]
  name = "Doc"
  url = "/docs"
  weight = 30

[[main]]
  name = "Contact"
  url = "/contact"
  weight = 60

[[main_right]]
  name = "<i class=\"fab fa-github-alt\" style=\"color: #333; font-size: 1rem; line-height: 1.25\"></i>"
  post = ""
  url = "https://github.com/benasse/sparrow"
  weight = 10

[[docs]]
  name = "Getting Started"
  weight = 10
  url = "/docs/"
  identifier = "getting-started"

[[docs]]
  name = "Hardware"
  weight = 20
  url = "/docs/hardware"
  identifier = "hardware"

[[docs]]
  name = "Validated hardware"
  weight = 31
  url = "../hardware#validated-hardware"
  parent = "hardware"

[[docs]]
  name = "Compatible hardware"
  weight = 32
  url = "../hardware#compatible-hardware"
  parent = "hardware"

[[docs]]
  name = "Install"
  weight = 30
  url = "/docs/install"
  identifier = "installation"

[[docs]]
  name = "Requirements"
  weight = 31
  url = "../install#requirements"
  parent = "installation"

[[docs]]
  name = "Installation"
  weight = 32
  url = "../install#installation"
  parent = "installation"

[[docs]]
  name = "Troubleshooting"
  weight = 50
  url = "/docs/troubleshooting/"
  identifier = "troubleshooting"

[[docs]]
  name = "Tips"
  weight = 60
  url = "/docs/tips/"
  identifier = "tips"

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
